;; Copyright (c) 2026 Will Cohen
;;
;; Part of clj-gdal, under the MIT License.
;; See LICENSE for license information.
;; SPDX-License-Identifier: MIT

(ns hooks.gdal
  "clj-kondo hooks for the fns that clj-gdal makes from its fndefs.
   `c-names` holds the C names, because a hook runs in SCI and cannot read
   fndefs. bb kondo:fndefs writes the list."
  (:require [clj-kondo.hooks-api :as api]
            [hooks.native.generated :as gen]))

;; >>> BEGIN GENERATED by bb kondo:fndefs from fndefs.cljc
(def c-names
  [:CPLErrorReset
   :CPLErrorSetState
   :CPLGetConfigOption
   :CPLGetLastErrorMsg
   :CPLGetLastErrorNo
   :CPLHTTPSetFetchCallback
   :CPLMalloc
   :CPLSetConfigOption
   :CSLAddString
   :CSLDestroy
   :GDALAllRegister
   :GDALBuildOverviews
   :GDALClose
   :GDALCreate
   :GDALCreateCopy
   :GDALDatasetCommitTransaction
   :GDALDatasetCreateLayer
   :GDALDatasetExecuteSQL
   :GDALDatasetGetLayer
   :GDALDatasetGetLayerByName
   :GDALDatasetGetLayerCount
   :GDALDatasetReleaseResultSet
   :GDALDatasetRollbackTransaction
   :GDALDatasetStartTransaction
   :GDALGetBlockSize
   :GDALGetDataTypeName
   :GDALGetDatasetDriver
   :GDALGetDescription
   :GDALGetDriver
   :GDALGetDriverByName
   :GDALGetDriverCount
   :GDALGetDriverLongName
   :GDALGetDriverShortName
   :GDALGetFileList
   :GDALGetGeoTransform
   :GDALGetMetadata
   :GDALGetMetadataItem
   :GDALGetOverview
   :GDALGetOverviewCount
   :GDALGetProjectionRef
   :GDALGetRasterBand
   :GDALGetRasterBandXSize
   :GDALGetRasterBandYSize
   :GDALGetRasterCount
   :GDALGetRasterDataType
   :GDALGetRasterNoDataValue
   :GDALGetRasterXSize
   :GDALGetRasterYSize
   :GDALGetSpatialRef
   :GDALInfo
   :GDALInfoOptionsFree
   :GDALInfoOptionsNew
   :GDALOpen
   :GDALOpenEx
   :GDALRasterIO
   :GDALSetGeoTransform
   :GDALSetProjection
   :GDALSetRasterNoDataValue
   :GDALTranslate
   :GDALTranslateOptionsFree
   :GDALTranslateOptionsNew
   :GDALVectorInfo
   :GDALVectorInfoOptionsFree
   :GDALVectorInfoOptionsNew
   :GDALVectorTranslate
   :GDALVectorTranslateOptionsFree
   :GDALVectorTranslateOptionsNew
   :GDALVersionInfo
   :GDALWarp
   :GDALWarpAppOptionsFree
   :GDALWarpAppOptionsNew
   :OCTDestroyCoordinateTransformation
   :OCTNewCoordinateTransformation
   :OCTTransform
   :OGR_FD_GetFieldCount
   :OGR_FD_GetFieldDefn
   :OGR_FD_GetGeomFieldCount
   :OGR_FD_GetGeomFieldDefn
   :OGR_FD_GetGeomFieldIndex
   :OGR_FD_GetGeomType
   :OGR_F_Create
   :OGR_F_Destroy
   :OGR_F_GetFID
   :OGR_F_GetFieldAsBinary
   :OGR_F_GetFieldAsDateTime
   :OGR_F_GetFieldAsDateTimeEx
   :OGR_F_GetFieldAsDouble
   :OGR_F_GetFieldAsDoubleList
   :OGR_F_GetFieldAsInteger
   :OGR_F_GetFieldAsInteger64
   :OGR_F_GetFieldAsInteger64List
   :OGR_F_GetFieldAsIntegerList
   :OGR_F_GetFieldAsString
   :OGR_F_GetFieldAsStringList
   :OGR_F_GetFieldDefnRef
   :OGR_F_GetFieldIndex
   :OGR_F_GetGeomFieldRef
   :OGR_F_GetGeometryRef
   :OGR_F_IsFieldNull
   :OGR_F_IsFieldSet
   :OGR_F_IsFieldSetAndNotNull
   :OGR_F_SetFID
   :OGR_F_SetFieldBinary
   :OGR_F_SetFieldDateTime
   :OGR_F_SetFieldDateTimeEx
   :OGR_F_SetFieldDouble
   :OGR_F_SetFieldDoubleList
   :OGR_F_SetFieldInteger
   :OGR_F_SetFieldInteger64
   :OGR_F_SetFieldInteger64List
   :OGR_F_SetFieldIntegerList
   :OGR_F_SetFieldNull
   :OGR_F_SetFieldString
   :OGR_F_SetFieldStringList
   :OGR_F_SetGeomField
   :OGR_F_SetGeomFieldDirectly
   :OGR_F_SetGeometryDirectly
   :OGR_F_UnsetField
   :OGR_Fld_Create
   :OGR_Fld_Destroy
   :OGR_Fld_GetDefault
   :OGR_Fld_GetNameRef
   :OGR_Fld_GetPrecision
   :OGR_Fld_GetSubType
   :OGR_Fld_GetTZFlag
   :OGR_Fld_GetType
   :OGR_Fld_GetWidth
   :OGR_Fld_IsNullable
   :OGR_Fld_IsUnique
   :OGR_Fld_SetDefault
   :OGR_Fld_SetNullable
   :OGR_Fld_SetPrecision
   :OGR_Fld_SetSubType
   :OGR_Fld_SetTZFlag
   :OGR_Fld_SetUnique
   :OGR_Fld_SetWidth
   :OGR_GFld_Create
   :OGR_GFld_Destroy
   :OGR_GFld_GetNameRef
   :OGR_GFld_GetSpatialRef
   :OGR_GFld_GetType
   :OGR_GFld_SetNullable
   :OGR_GFld_SetSpatialRef
   :OGR_G_CreateFromWkb
   :OGR_G_CreateFromWkt
   :OGR_G_CreateGeometryFromJson
   :OGR_G_DestroyGeometry
   :OGR_G_ExportToIsoWkb
   :OGR_G_ExportToIsoWkt
   :OGR_G_ExportToJson
   :OGR_G_ExportToJsonEx
   :OGR_G_ExportToWkb
   :OGR_G_ExportToWkt
   :OGR_G_GetEnvelope
   :OGR_G_GetGeometryType
   :OGR_G_WkbSize
   :OGR_L_CreateFeature
   :OGR_L_CreateField
   :OGR_L_CreateGeomField
   :OGR_L_DeleteFeature
   :OGR_L_GetExtent
   :OGR_L_GetFIDColumn
   :OGR_L_GetFeature
   :OGR_L_GetFeatureCount
   :OGR_L_GetGeomType
   :OGR_L_GetGeometryColumn
   :OGR_L_GetLayerDefn
   :OGR_L_GetName
   :OGR_L_GetNextFeature
   :OGR_L_GetSpatialRef
   :OGR_L_ResetReading
   :OGR_L_SetAttributeFilter
   :OGR_L_SetFeature
   :OGR_L_SetIgnoredFields
   :OGR_L_SetNextByIndex
   :OGR_L_SetSpatialFilter
   :OGR_L_SetSpatialFilterRect
   :OGR_L_SyncToDisk
   :OGR_L_TestCapability
   :OGR_L_UpdateFeature
   :OGR_L_UpsertFeature
   :OSRAutoIdentifyEPSG
   :OSRClone
   :OSRDestroySpatialReference
   :OSRExportToPROJJSON
   :OSRExportToWkt
   :OSRExportToWktEx
   :OSRGetAuthorityCode
   :OSRGetAuthorityName
   :OSRGetName
   :OSRImportFromEPSG
   :OSRIsGeographic
   :OSRIsProjected
   :OSRIsSame
   :OSRNewSpatialReference
   :OSRSetAxisMappingStrategy
   :OSRSetFromUserInput
   :VSIFCloseL
   :VSIFileFromMemBuffer
   :VSIFree
   :VSIGetMemFileBuffer
   :VSIMalloc
   :VSIReadDir
   :VSIUnlink])
;; <<< END GENERATED

(def ^:private fndefs-keys (zipmap c-names (repeat nil)))

(defn define-all-gdal-public-fns
  "Declare each fn that the macro makes, with no arity, because the hook
   has only the C names. The node also refers to gdal-call or dispatch-gdal,
   because clj-kondo otherwise reports that private fn as unused."
  [{:keys [lang]}]
  {:node (api/list-node
          [(api/token-node 'do)
           (gen/declare-node fndefs-keys gen/camel-name->clj-name)
           (api/token-node (if (= :cljs lang) 'dispatch-gdal 'gdal-call))])})
