;; Copyright (c) 2026 Will Cohen
;;
;; Part of clj-gdal, under the MIT License.
;; See LICENSE for license information.
;; SPDX-License-Identifier: MIT

(ns lint
  "Run clj-kondo with the hooks of this project and of its dependencies, and
   keep the C names of the exported hook in step with fndefs. The configs of
   the dependencies come from .clj-kondo/imports."
  (:require [babashka.fs :as fs]
            [babashka.process :as p]
            [clojure.string :as str]
            [native-dev]
            [net.willcohen.gdal.fndefs :as fndefs]))

;; Not the default .clj-kondo/.cache, because clojure-lsp writes its own
;; index there.
(def ^:private cache-dir ".clj-kondo/.cache-cli")

(def ^:private hook "resources/clj-kondo.exports/net.willcohen/gdal/hooks/gdal.clj")

(def ^:private begin-marker ";; >>> BEGIN GENERATED by bb kondo:fndefs from fndefs.cljc")

(def ^:private end-marker ";; <<< END GENERATED")

(defn- names-form []
  (str "(def c-names\n  ["
       (str/join "\n   " (sort (map str (keys fndefs/fndefs))))
       "])"))

(defn- splice [text form]
  (let [begin (str/index-of text begin-marker)
        end   (str/index-of text end-marker)]
    (when-not (and begin end (< begin end))
      (throw (ex-info "The hook has no generated-region markers" {:hook hook})))
    (str (subs text 0 (+ begin (count begin-marker)))
         "\n" form "\n"
         (subs text end))))

(defn sync-hook!
  "Write the C names of fndefs into the exported hook. A consumer reads a
   name that the hook lacks as `Unresolved var`. With `check?`, write
   nothing, and throw when the names do not agree."
  [check?]
  (let [text    (slurp hook)
        updated (splice text (names-form))]
    (cond
      (= text updated)
      (println (str hook " is up to date"))

      check?
      (throw (ex-info (str hook " does not agree with fndefs.cljc. Run bb kondo:fndefs and commit the result.")
                      {:hook hook}))

      :else
      (do (spit hook updated)
          (println (str "Wrote " hook))))))

(defn- kondo! [& args]
  (apply p/shell "clj-kondo" (concat args ["--cache-dir" cache-dir])))

(defn deps!
  "Index the classpath, and copy the dependency configs for clj-kondo.
   The configs go into .clj-kondo/imports, and the index into the cache."
  []
  ;; Two class paths, because the :deps of :build replace the project deps.
  (let [spath #(str/trim (:out (p/shell {:out :string} "clojure" (str "-A" %) "-Spath")))
        cp    (str (spath (native-dev/aliases ":test")) java.io.File/pathSeparator (spath ":build"))]
    ;; Two passes, because --dependencies ignores --copy-configs. The hook of
    ;; this repo requires hooks.native.generated from the net.willcohen/native
    ;; config.
    (kondo! "--lint" cp "--copy-configs" "--skip-lint")
    ;; resources is on the class path, thus the copy holds an old export of
    ;; this repo. config.edn reads the export in resources.
    (fs/delete-tree ".clj-kondo/imports/net.willcohen/gdal")
    (kondo! "--lint" cp "--dependencies" "--parallel")))

(defn lint!
  "Lint src, test, scripts, dev and build.clj.
   Index the dependencies first when there is no cache, and check the hook
   names against fndefs."
  []
  (when-not (and (fs/exists? cache-dir) (fs/exists? ".clj-kondo/imports/net.willcohen/native"))
    (println "No clj-kondo dependency cache or imported configs. Indexing the classpath once (see lint:deps).")
    (deps!))
  (sync-hook! true)
  (kondo! "--lint" "src" "test" "scripts" "dev" "build.clj"))
